language: node_js
node_js:
  - '6'
deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy.sh
  'on':
    branch: src
    node: '6'
env:
  global:
    - secure: >-
        Asr2yvBulC9oxmCcyLiq+SNa/uk96julfNHeaD4FuD9aNa7oTpaTn9kKO2O4OqVHKAgTEr/ZDYznBX8dIRSjY8rdbuD26/yr55/adVX17Kz8AywPOhVjKqzB4Qvv58p0SZJZV9bANouGsRXhFToj3pMxB1UZL2l+o2wcC7c5gUXmuY23XrkCdgSPUC8JisW3faflwwVgeBCqq6ivO7QqAx+sRGViGwKybipLkeeS+gW9y4nz90Iycy0kji9c6Xp/sPZlRVRy50HOVt5n1F76zxd/yeJDhz70Ovr7Ekm+0fFcyxWOJMT9GKL86UVb53H+9FKWvw+BmxIbaQ7Icy/DnlnJMD1HEhhprJGqGqPFxmKWMGDvQRi/3HomgL8qpZ65TIvtTQoItRqKd9+Y9XCMAo8AF3VkTibprGMYGz6SHw1ND35cMVQewHNAEaNmYcESOW9GnVip955814wmWpzlSPWXBv85YGo7ZFToEv+I3Bb4OEPYcNoMREyYO78oqYQDL0rgEp6sorKYlM0CdYEAfp05h51OJ+unGJvp/9epDJZIjplBRURI9ZOAMP7rvMlgl5A+3Cyx32C2ERpyChuK37NyK1tlBLLR/jRKqV6RTosXF8wcJP2UmRALeHAGdQDp1shnUhvP/5z8rlB+Mdi1OE3A+TS04f1FkJxFpn4pmA8=
    - GIT_DEPLOY_REPO=https://$GITHUB_TOKEN@github.com/J0hn-/j0hn-.github.io.git
